---
- name: Setup kubectl autocomplete and alias
  hosts: masters
  become: no
  gather_facts: yes
  
  tasks:
    - name: Setup kubectl bash completion
      shell: echo "source <(kubectl completion bash)" >> ~/.bashrc
      args:
        executable: /bin/bash
      register: kubectl_completion
      changed_when: false
      
    - name: Create kubectl alias 'k'
      shell: |
        echo "alias k=kubectl" >> ~/.bashrc
        echo "complete -o default -F __start_kubectl k" >> ~/.bashrc
      args:
        executable: /bin/bash
      register: kubectl_alias
      changed_when: false
      
    - name: Reload bashrc
      shell: source ~/.bashrc
      args:
        executable: /bin/bash
      register: bashrc_reload
      changed_when: false
      
    - name: Display kubectl setup completion
      debug:
        msg: "{{ inventory_hostname }}: kubectl autocomplete and alias 'k' setup completed"
