---
- name: Install ArgoCD CLI
  hosts: master1
  become: yes
  gather_facts: yes
  
  vars:
    argocd_cli_version: "latest"
    argocd_install_dir: "/usr/local/bin"
    
  tasks:
    - name: Check if ArgoCD CLI is already installed
      command: argocd version --client
      register: argocd_cli_check
      failed_when: false
      changed_when: false
      
    - name: Display current ArgoCD CLI version if installed
      debug:
        msg: "ArgoCD CLI is already installed: {{ argocd_cli_check.stdout }}"
      when: argocd_cli_check.rc == 0
      
    - name: Skip installation if ArgoCD CLI is already installed
      meta: end_host
      when: argocd_cli_check.rc == 0
      
    - name: Create temporary directory for ArgoCD CLI download
      tempfile:
        state: directory
        suffix: argocd-cli
      register: temp_dir
      
    - name: Download ArgoCD CLI binary (latest version)
      get_url:
        url: "https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64"
        dest: "{{ temp_dir.path }}/argocd"
        mode: '0755'
        timeout: 30
      register: argocd_download
      
    - name: Install ArgoCD CLI binary
      copy:
        src: "{{ temp_dir.path }}/argocd"
        dest: "{{ argocd_install_dir }}/argocd"
        mode: '0755'
        remote_src: yes
        backup: yes
        
    - name: Verify ArgoCD CLI installation
      command: argocd version --client
      register: argocd_cli_verify
      
    - name: Display ArgoCD CLI installation success
      debug:
        msg: "ArgoCD CLI successfully installed: {{ argocd_cli_verify.stdout }}"
        
    - name: Clean up temporary directory
      file:
        path: "{{ temp_dir.path }}"
        state: absent
        
    - name: Add ArgoCD CLI autocompletion for bash
      shell: |
        argocd completion bash | tee /etc/bash_completion.d/argocd > /dev/null
      register: argocd_completion
      failed_when: false
      
    - name: Display ArgoCD CLI completion setup result
      debug:
        msg: "ArgoCD CLI bash completion {{ 'enabled' if argocd_completion.rc == 0 else 'failed to enable' }}"
        
    - name: Test ArgoCD CLI help command
      command: argocd --help
      register: argocd_help
      failed_when: false
      
    - name: Display ArgoCD CLI help test result
      debug:
        msg: "ArgoCD CLI help command {{ 'working' if argocd_help.rc == 0 else 'failed' }}"
        
    - name: Display installation completion
      debug:
        msg: |
          {{ inventory_hostname }}: ArgoCD CLI installation completed successfully!
          
          Next steps:
          1. Get the admin password:
             kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
          
          2. Login to ArgoCD:
             argocd login argo.ochukowhoro.xyz --insecure --username admin
          
          3. Or skip TLS verification:
             argocd login argo.ochukowhoro.xyz --insecure --grpc-web
          
          4. Access the web UI:
             https://argo.ochukowhoro.xyz
