all:
  hosts:
    master1:
      ansible_connection: ssh
      ansible_host: master1
    worker1:
      ansible_connection: ssh
      ansible_host: worker1
    worker2:
      ansible_connection: ssh
      ansible_host: worker2
  children:
    masters:
      hosts:
        master1:
      vars:
        ansible_user: vagrant
        ansible_ssh_common_args: '-F ssh_config'
    workers:
      hosts:
        worker1:
        worker2:
      vars:
        ansible_user: vagrant
        ansible_ssh_common_args: '-F ssh_config'
